[launcher]
author=Gyver (tcgyver@gmail.com)
description=MCPAgents Enterprise AI Control Center — Splunk Integration
version=2.0.0

[ui]
is_visible=1
label=MCPAgents AI Ops

[package]
id=mcpagents_splunk
check_for_updates=1
